use_frameworks!

target 'MyTextView_Example' do
  pod 'MyTextView', :path => '../'

  target 'MyTextView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
